Repository chanzuckerberg/czgenepi, pull requests merged in 2021-09, with the labels that each got.

#655 Maya/filter styles
  src/frontend/src/components/FilterPanel/index.tsx
  src/frontend/src/views/Data/components/FilterPanelToggle/index.tsx
  src/frontend/src/views/Data/index.tsx
Labels: enhancement

#669 [ch160837] filter state panel toggle
  src/frontend/src/components/FilterPanel/index.tsx
  src/frontend/src/components/FilterPanel/style.ts
  src/frontend/src/views/Data/index.tsx
Labels: enhancement

#668 [ch160824] exclude na dates
  src/frontend/src/components/FilterPanel/index.tsx
Labels: enhancement

#674 [ch160840] filter count styles
  src/frontend/src/common/icons/IconFilters.svg
  src/frontend/src/views/Data/components/FilterPanelToggle/index.tsx
  src/frontend/src/views/Data/components/FilterPanelToggle/style.ts
Labels: enhancement

#675 [ch153503] phylo tree help link
  src/frontend/src/common/components/library/data_subview/components/TreeCreateHelpLink/index.tsx
  src/frontend/src/common/components/library/data_subview/components/TreeCreateHelpLink/styles.ts
  src/frontend/src/common/components/library/data_subview/index.tsx
  src/frontend/src/common/icons/IconArrowRightSmall.svg
  src/frontend/src/common/icons/IconInsightSmall.svg
Labels: enhancement

#678 tree type tooltips
  src/frontend/src/views/Data/cellRenderers.tsx
  src/frontend/src/views/Data/components/TreeTypeTooltip/index.tsx
  src/frontend/src/views/Data/headerRenderer.tsx
  src/frontend/src/views/Data/index.tsx
Labels: enhancement

#680 add fontCapsXxxs
  src/frontend/src/components/FilterPanel/style.ts
Labels: enhancement

#679 [sc161296] disable view download failed
  src/frontend/src/common/constants/types.ts
  src/frontend/src/components/TreeTableDownloadMenu/index.tsx
  src/frontend/src/views/Data/cellRenderers.tsx
  src/frontend/src/views/Data/components/TreeTableNameCell/index.tsx
  src/frontend/src/views/Data/components/TreeTableNameCell/style.ts
Labels: enhancement

#682 Maya/161303 161299 tooltips
  src/frontend/src/common/components/library/data_table/style.ts
  src/frontend/src/views/Data/cellRenderers.tsx
  src/frontend/src/views/Data/headers.tsx
  src/frontend/src/views/Data/style.ts
Labels: bug

#684 Maya/150460 status tags
  src/frontend/src/common/components/library/data_table/index.module.scss
  src/frontend/src/common/components/library/data_table/index.tsx
  src/frontend/src/common/components/library/data_table/style.ts
  src/frontend/src/common/types/bioinformatics.d.ts
  src/frontend/src/views/Data/components/TreeTableNameCell/components/PhyloTreeStatusTag/index.tsx
  src/frontend/src/views/Data/components/TreeTableNameCell/components/PhyloTreeStatusTag/style.ts
  src/frontend/src/views/Data/components/TreeTableNameCell/index.tsx
  src/frontend/src/views/Data/components/TreeTableNameCell/style.ts
Labels: enhancement

#687 allow all tree statuses
  src/frontend/src/views/Data/index.tsx
Labels: bug

#690 add setTreeNameTooLong to clearState
  src/frontend/src/common/components/library/data_subview/components/createTreeModal/index.tsx
Labels: enhancement

#691 disable download when tree status is incomplete or failed
  src/frontend/src/components/TreeTableDownloadMenu/index.tsx
Labels: bug, design feedback

#692 replacing creationDate with StartedDate
  src/frontend/src/views/Data/headers.tsx
  src/frontend/src/views/Data/index.tsx
Labels: enhancement

#695 update debug wdl to add tree type arg
  .happy/terraform/modules/sfn_config/nextstrain-dbg.wdl
Labels: bug

#697 strip leading and trailing whitespace
  src/cli/aspencli.py
Labels: enhancement

#699 add error 600 text
  src/frontend/src/components/FilterPanel/components/DateFilter/style.ts
Labels: design feedback

#698 [sc137430] reorder columns
  src/frontend/src/views/Data/headers.tsx
Labels: enhancement

#704 Danrlu/add tree description
  src/backend/aspen/workflows/nextstrain_run/builds_templates/group_plus_context.yaml
  src/backend/aspen/workflows/nextstrain_run/builds_templates/non_contextualized.yaml
  src/backend/aspen/workflows/nextstrain_run/builds_templates/targeted.yaml
  src/backend/aspen/workflows/nextstrain_run/nextstrain_profile/aspen_auspice_config_v2.json
  src/backend/aspen/workflows/nextstrain_run/nextstrain_profile/description_non_contextualized.md
  src/backend/aspen/workflows/nextstrain_run/nextstrain_profile/description_overview.md
  src/backend/aspen/workflows/nextstrain_run/nextstrain_profile/description_targeted.md
Labels: enhancement

#705 add pango lineage to Aspen metadata and allow filtering
  src/backend/aspen/workflows/nextstrain_run/export.py
  src/backend/aspen/workflows/nextstrain_run/nextstrain_profile/aspen_auspice_config_v2.json
Labels: bug

#709 Sc163454 acknowledge policy changes banner
  src/backend/aspen/app/views/usergroup.py
  src/backend/aspen/database/models/usergroup.py
  src/backend/database_migrations/versions/20210928_203749_add_users_column_of_acknowledged_policy_.py
  src/frontend/pages/_app.tsx
  src/frontend/src/common/icons/IconInfo.svg
  src/frontend/src/common/queries/auth.ts
  src/frontend/src/common/types/user.d.ts
  src/frontend/src/components/AcknowledgePolicyChanges/index.tsx
  src/frontend/src/components/AcknowledgePolicyChanges/style.ts
  src/frontend/src/views/AgreeTerms/index.tsx
  src/frontend/src/views/Privacy/index.tsx
  src/frontend/src/views/Terms/index.tsx
Labels: enhancement, migration, frontend, backend

#707 Maya/feature flags
  src/frontend/pages/_app.tsx
  src/frontend/src/common/components/library/data_table/index.tsx
  src/frontend/src/common/utils/featureFlags.tsx
  src/frontend/src/common/utils/localStorage.tsx
Labels: enhancement

#711 Handle Nextstrain batch failures
  .happy/terraform/modules/sfn_config/nextstrain-ondemand.wdl
  .happy/terraform/modules/sfn_config/nextstrain.wdl
  src/backend/aspen/workflows/nextstrain_run/error.py
  src/backend/aspen/workflows/nextstrain_run/run_nextstrain_ondemand.sh
  src/backend/aspen/workflows/nextstrain_run/run_nextstrain_scheduled.sh
Labels: bug, backend
