Repository chanzuckerberg/czgenepi, pull requests merged in 2021-08, with the labels that each got.

#620 doc updates
  docs/DEV_ENV.md
  docs/REMOTE_DEV.md
Labels: documentation

#622 [ch143538] hide columns when no samples have been submitted to gisaid
  src/frontend/src/views/Upload/components/Metadata/components/Table/components/Row/components/FreeTextField/index.tsx
  src/frontend/src/views/Upload/components/Metadata/components/Table/components/Row/components/FreeTextField/style.ts
  src/frontend/src/views/Upload/components/Metadata/components/Table/index.tsx
Labels: bug

#626 [ch149228] showing table loading animation before data is loaded
  src/frontend/src/common/components/library/data_table/index.tsx
Labels: bug

#627 add small note about underscores in rdev names
  docs/REMOTE_DEV.md
Labels: documentation

#628 remove extraneous paren
  src/frontend/src/common/components/library/data_table/index.tsx
Labels: bug

#629 [ch150281] add the most basic filter panel possible to the sample table
  src/frontend/src/common/components/library/data_subview/index.module.scss
  src/frontend/src/common/components/library/data_subview/index.tsx
  src/frontend/src/common/components/library/data_subview/style.ts
  src/frontend/src/components/FilterPanel/index.tsx
  src/frontend/src/components/FilterPanel/style.ts
  src/frontend/src/views/Data/index.module.scss
  src/frontend/src/views/Data/index.tsx
  src/frontend/src/views/Data/style.ts
Labels: enhancement

#633 [ch150281] filter panel toggle
  src/frontend/src/common/components/library/data_subview/components/DownloadModal/style.ts
  src/frontend/src/common/components/library/data_subview/index.tsx
  src/frontend/src/common/components/library/data_subview/style.ts
  src/frontend/src/common/constants/types.ts
  src/frontend/src/common/icons/IconFilters.svg
  src/frontend/src/common/styles/support/style.ts
  src/frontend/src/common/types/data.d.ts
  src/frontend/src/components/FilterPanel/style.ts
  src/frontend/src/views/Data/components/FilterPanelToggle/index.tsx
  src/frontend/src/views/Data/components/FilterPanelToggle/style.ts
  src/frontend/src/views/Data/index.module.scss
  src/frontend/src/views/Data/index.tsx
Labels: enhancement

#636 change table text to fontBodyXs
  src/frontend/src/common/components/library/data_table/index.module.scss
Labels: bug

#642 [ch150283] date picker
  src/frontend/src/common/components/library/data_subview/index.tsx
  src/frontend/src/common/components/library/data_table/index.tsx
  src/frontend/src/components/DateField/constants.ts
  src/frontend/src/components/DateField/index.tsx
  src/frontend/src/components/DateField/style.ts
  src/frontend/src/components/FilterPanel/components/CollectionDateFilter/index.tsx
  src/frontend/src/components/FilterPanel/components/CollectionDateFilter/style.ts
  src/frontend/src/components/FilterPanel/index.tsx
  src/frontend/src/views/Data/index.tsx
  src/frontend/src/views/Upload/components/Metadata/components/Table/components/Row/components/UploadDateField/index.tsx
  src/frontend/src/views/Upload/components/Metadata/components/Table/components/Row/index.tsx
Labels: enhancement

#648 [ch150285] lineage filter
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/common/components/library/data_subview/components/DownloadModal/index.tsx
  src/frontend/src/common/components/library/data_table/index.tsx
  src/frontend/src/components/FilterPanel/components/LineageFilter/index.tsx
  src/frontend/src/components/FilterPanel/index.tsx
  src/frontend/src/views/Data/index.tsx
  src/frontend/src/views/Upload/components/Metadata/components/ImportFile/index.tsx
  src/frontend/src/views/Upload/components/Review/index.tsx
  src/frontend/src/views/Upload/components/Samples/components/Table/index.tsx
Labels: enhancement

#651 [ch150281] genome recovery filter
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/components/FilterPanel/components/GenomeRecoveryFilter/index.tsx
  src/frontend/src/components/FilterPanel/index.tsx
  src/frontend/src/components/FilterPanel/style.ts
Labels: enhancement

#653 Maya/filter styles
  src/frontend/src/components/DateField/index.tsx
  src/frontend/src/components/DateField/style.ts
  src/frontend/src/components/FilterPanel/components/CollectionDateFilter/index.tsx
  src/frontend/src/components/FilterPanel/components/DateFilter/index.tsx
  src/frontend/src/components/FilterPanel/components/DateFilter/style.ts
  src/frontend/src/components/FilterPanel/components/GenomeRecoveryFilter/index.tsx
  src/frontend/src/components/FilterPanel/components/LineageFilter/index.tsx
  src/frontend/src/components/FilterPanel/components/UploadDateFilter/index.tsx
  src/frontend/src/components/FilterPanel/style.ts
  src/frontend/src/views/Upload/components/Metadata/components/Table/components/Row/index.tsx
  src/frontend/src/views/Upload/components/Metadata/components/Table/components/Row/style.ts
Labels: enhancement
